# configs/default.yaml — HeRALD (HGAT-LDA) — LOOCV/AUC-optimized

model:
  emb_dim: 256
  num_layers: 3              # shallower = less over-smoothing on small graphs
  dropout: 0.35
  num_heads: 4               # 256 % 4 == 0  → head_dim=64
  relation_dropout: 0.2      # a bit more regularization for stability
  use_layernorm: true
  use_residual: true
  use_relation_norm: true    # normalize per relation (D^-1 A)
  score_orientation: auto    # affinity | distance | auto (default: auto)

training:
  # Optimizer/schedule
  lr: 0.00038
  weight_decay: 7.44e-05
  batch_size: 128
  num_epochs: 30             # align with cosine_tmax
  cosine_tmax: 30

  # Loss (AUC-first)
  loss_type: pairwise        # pairwise | bce | focal
  pairwise_type: auc         # auc (logistic) | bpr
  use_hard_negatives: true   # semi-hard mining inside trainer
  label_smoothing: 0.0       # do not smooth for pairwise

  # BCE fallback settings (kept for compatibility; ignored in pairwise)
  use_focal_loss: false
  neg_ratio: 3

  # General stability
  gradient_clip: 1.0
  val_split: 0.0             # LOOCV per-fold; no random val split
  early_stopping_patience: 0 # not used with val_split=0

data:
  data_dir: Dataset
  threshold: 0.0
  symmetric: true

  # Similarity graph hygiene
  sim_topk: 30               # try 20/30/40 if you sweep
  sim_mutual: true           # mutual-kNN (bidirectional)
  sim_sym: true              # symmetrize after filtering
  sim_row_norm: true         # row-stochastic
  sim_row_normalize: true    # legacy key (kept true for safety)
  sim_tau: null              # optional softmax temperature (e.g., 0.8)

  # Bipartite relations
  use_bipartite_edge_weight: true  # tf-idf/degree-style weights

eval:
  protocol: loocv_pair       # per-positive LOOCV
  rewrite_isolated: true     # rewrite disease row/col when isolated
  full_ranking: true         # rank all candidates (no neg sampling)

system:
  device: auto
  seed: 42
  num_workers: 8             # safer default; raise if your loader is stable
  use_amp: true
  pin_memory: true
  prefetch_factor: 4
