model:
  emb_dim: 256               # Updated per tuning
  num_layers: 4              # Updated per tuning
  dropout: 0.35              # Updated per tuning
  num_heads: 6               # Updated per tuning
  relation_dropout: 0.1      # Updated per tuning
  use_layernorm: true        # Use LayerNorm for stable training
  use_residual: true         # Use residual connections

training:
  lr: 0.0003762875402329099  # Updated per tuning
  weight_decay: 7.438974554514027e-05  # Updated per tuning
  batch_size: 128             # Updated per tuning
  num_epochs: 50              # Keep as is unless tuned separately
  val_split: 0.15             # Standard validation split
  early_stopping_patience: 10 # Reasonable patience
  neg_ratio: 3                # Updated per tuning
  cosine_tmax: 50             # Updated per tuning
  use_focal_loss: false       # Updated per tuning
  label_smoothing: 0.05       # Updated per tuning
  gradient_clip: 1.0          # Gradient clipping for stability


data:
  threshold: 0.0
  symmetric: true
  data_dir: Dataset
  sim_row_normalize: true     # Normalize similarity matrices
  sim_topk: 30                # Keep top-30 neighbors (sweet spot)

system:
  device: auto                # Device: auto, cuda, cpu
  seed: 42                    # Random seed
  num_workers: 32             # Many workers for 64-core CPU
  use_amp: true               # Enable AMP for RTX 5090
  pin_memory: true            # Pin memory for faster GPU transfer
  prefetch_factor: 4          # Prefetch batches for efficiency